# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('key', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting Approval'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('hosts', models.ManyToManyField(blank=True, to='app.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Rsyslog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=32)),
                ('dates', models.DateField(null=True)),
                ('ltime', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=64)),
                ('result', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sendmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=32)),
                ('program', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('dates', models.DateField(null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=60)),
                ('telephone', models.CharField(max_length=30)),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uptime', models.DateTimeField(auto_now=True, null=True)),
                ('user_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.UserRole'),
        ),
    ]
